
############## REDIS ##############
FROM redis:5.0-alpine
ENV REDIS_VERSION 5.0

EXPOSE 6379

CMD [ "redis-server"]

# Command to run on start
#CMD [ "redis-server", "/usr/local/etc/redis/redis.conf" ]